### ISSUE TITLE
Format rose plots

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#20]
Can you change the format of teh rose plots a little? I would standard like to show 3 roseplots (e.g. start mid and end of an operation). In the current format showing 3 plots in a row, the actual figure become to small. 

Can you leave out the dominant wave direction (this is clearly shown in the rose plot). 
Can you make the text size of the directions and the wave periods small such that the actual plot becomes a little bigger. 

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/08d196bd-2a50-4f65-9a7d-68da74218ee9)

**Comment by RubendeBruin** [comment]
@JorickVel , Like so?
Title size 10
Other text size 6

![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/eb411dc4-ac8f-4f27-8b74-9506f9691687)

Can also do North, East etc instead of numbers:
![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/8e24c4ee-d2cd-46ad-b6b6-8e8379994c21)

**Comment by JorickVel** [comment]
Yes nice. I think N NW notation is the better option.
